#!/bin/bash
#SBATCH --account=s1152
#SBATCH --job-name="cdo_remapping"
#SBATCH --time=0:10:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=debug
#SBATCH --constraint=mc

module load daint-gpu
module load gcc/9.3.0
module load CDO
module load NCO

export PMI_MMAP_SYNC_WAIT_TIME=300
export OMP_NUM_THREADS=1
export OMP_SCHEDULE="static"
export OMP_DYNAMIC="false"
export RLIMIT_CORE=0
export ATP_MAX_CORES=0

remap_method=remapcon

DATAFILELIST=$(find /store/empa/em05/dbrunner/icon-art/meteo/ifs_2018010[1-2]*.grb)

cdo -t ecmwf -f nc copy /store/empa/em05/dbrunner/icon-art/meteo/ifs_2018010100.grb tmp1.nc
cdo setpartabn,mypartab,convert tmp1.nc tmp2.nc


rm tmp1.nc


cdo -s selname,LSM tmp2.nc input_FR_LAND.nc
ncrename -h -v LSM,FR_LAND input_FR_LAND.nc
cdo -s selname,FR_LAND extpar.nc output_FR_LAND.nc
ncecat -O -u time output_FR_LAND.nc output_FR_LAND.nc # add time dimension otherwise ICON stops
ncks -h -A -v time input_FR_LAND.nc output_FR_LAND.nc # give time a value to avoid CDO warnings
cdo -L setctomiss,0. -ltc,0.5  input_FR_LAND.nc input_ocean_area.nc
cdo -L setctomiss,0. -gec,0.5 input_FR_LAND.nc input_land_area.nc
cdo -L setctomiss,0. -ltc,1. output_FR_LAND.nc output_ocean_area.nc
cdo -L setctomiss,0. -gtc,0. output_FR_LAND.nc output_land_area.nc
cdo -L setrtoc2,0.5,1.0,1,0 output_FR_LAND.nc output_lsm.nc
rm input_FR_LAND.nc output_FR_LAND.nc


# create file with ICON grid information for CDO
cdo -s selgrid,2 dyn_grid.nc triangular-grid.nc


# remap land area only variables (ocean points are assumed to be undefined in the input data)
cdo -s setmisstodis -selname,SMIL1,SMIL2,SMIL3,SMIL4,STL1,STL2,STL3,STL4,W_SNOW,T_SNOW tmp2.nc tmpl1.nc
cdo -s ${remap_method},triangular-grid.nc tmpl1.nc tmpl2.nc
# cdo -s div tmpl2.nc output_land_area.nc tmp_output_l.nc
mv tmpl2.nc tmp_output_l.nc
rm tmpl*.nc

## remap land and ocean area differently for variables
# ocean part
cdo -s selname,SKT tmp2.nc tmp_input_ls.nc
cdo -s div tmp_input_ls.nc input_ocean_area.nc  tmpls1.nc
cdo -s setmisstodis tmpls1.nc tmpls2.nc
cdo -s ${remap_method},triangular-grid.nc tmpls2.nc tmpls3.nc
cdo -s div tmpls3.nc output_ocean_area.nc tmp_ocean_part.nc
rm tmpls*.nc output_ocean_area.nc input_ocean_area.nc

# land part
cdo -s div tmp_input_ls.nc input_land_area.nc  tmpls1.nc
cdo -s setmisstodis tmpls1.nc tmpls2.nc
cdo -s ${remap_method},triangular-grid.nc tmpls2.nc tmpls3.nc
cdo -s div tmpls3.nc output_land_area.nc tmp_land_part.nc
rm tmpls*.nc output_land_area.nc input_land_area.nc

# merge remapped land and ocean part
cdo -s ifthenelse output_lsm.nc tmp_land_part.nc  tmp_ocean_part.nc tmp_output_ls.nc
rm tmp_land_part.nc tmp_ocean_part.nc

# remap the rest
ncks -h -O -x -v W_SNOW,T_SNOW,STL1,STL2,STL3,STL4,SMIL1,SMIL2,SMIL3,SMIL4,SKT,LSM tmp2.nc tmp_input_rest.nc
cdo -s ${remap_method},triangular-grid.nc tmp_input_rest.nc ifs_ini.nc

# merge remapped files plus land sea mask from EXTPAR
ncks -h -A tmp_output_l.nc ifs_ini.nc
ncks -h -A tmp_output_ls.nc ifs_ini.nc
ncks -h -A output_lsm.nc  ifs_ini.nc
rm -f tmp_output_l.nc tmp_output_ls.nc tmp_input_ls.nc tmp_input_rest.nc output_lsm.nc


# attribute modifications
ncatted -h -a coordinates,FR_LAND,o,c,"clon clat" ifs_ini.nc

# renamings
ncrename -h -v FR_LAND,LSM ifs_ini.nc
ncrename -h -d cell,ncells ifs_ini.nc
ncrename -h -d nv,vertices ifs_ini.nc
ncrename -h -v u,U ifs_ini.nc
ncrename -h -v v,V ifs_ini.nc
ncrename -h -v w,W ifs_ini.nc
ncrename -h -v t,T ifs_ini.nc
ncrename -h -v q,QV ifs_ini.nc
ncrename -h -v z,GEOP_SFC ifs_ini.nc

cdo expr,"PS=exp(LNPS)" ifs_ini.nc PS.nc
cdo merge PS.nc ifs_ini.nc ifs_init.nc

rm -rf PS.nc ifs_ini.nc tmp2.nc




# lateral boundary grid
cdo -s selgrid,2 lateral_boundary.grid.nc boundary-grid.nc

for FILE in ${DATAFILELIST}; do
  echo ${FILE}
  FILEOUT=$(basename ${FILE} .grb)
  echo ${FILEOUT}
  cdo -t ecmwf -f nc copy ${FILE} tmp1.nc
  cdo setpartabn,mypartab,convert tmp1.nc tmp2.nc
  rm tmp1.nc
  if [[ $FILE == *00.grb ]] # * is used for pattern matching
  then
    echo ${FILEOUT}
    [ -e GEOSP.nc ] rm -rf GEOSP.nc
    cdo -s ${remap_method},boundary-grid.nc -selname,t,u,v,w,LNPS,q,QI,QR,QS,QC,GEOSP tmp2.nc ${FILEOUT}_lbc.nc
    cdo selvar,GEOSP ${FILEOUT}_lbc.nc GEOSP.nc
  else
    cdo -s ${remap_method},boundary-grid.nc -selname,t,u,v,w,LNPS,q,QI,QR,QC,QS tmp2.nc ${FILEOUT}_lbc.nc
    cdo merge ${FILEOUT}_lbc.nc GEOSP.nc merged.nc
    mv merged.nc ${FILEOUT}_lbc.nc
  fi
  ncrename -h -v u,U ${FILEOUT}_lbc.nc
  ncrename -h -v v,V ${FILEOUT}_lbc.nc
  ncrename -h -v w,W ${FILEOUT}_lbc.nc
  ncrename -h -v t,T ${FILEOUT}_lbc.nc
  ncrename -h -v q,QV ${FILEOUT}_lbc.nc
  ncrename -d cell,ncells ${FILEOUT}_lbc.nc
  ncrename -d nv,vertices ${FILEOUT}_lbc.nc

  rm -rf tmp2.nc
done

rm -rf GEOSP.nc
